# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2019 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest EXTRAS=docs,tests,elasticsearch
  - REQUIREMENTS=release EXTRAS=docs,tests,elasticsearch
  - REQUIREMENTS=devel EXTRAS=docs,tests,elasticsearch

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: QD2ZJ4Oyj4ykvT2uASsLWHUTEHY9cIp0WibRyrTJWFG8uQAPHGFtYNuNTXCP4XOrEFx0OHL6Om+YrsgYT1eR7Aj7GA84TCXcEuPmdQxFdgQuOdvP/jYJyuD1MY5Lf8GdC0m4VdRwm+92d7DCiYSkFwVFzidUtc/eyVdBi3Ay/Iw=
  distributions: "sdist bdist_wheel"
  on:
    python: "2.7"
    repo: inveniosoftware/invenio-query-parser
    tags: true
